services:
  no-ssl:
    image: ivo/portfolio_no_ssl
    build:
      dockerfile: Dockerfile-no-ssl
    ports:
      - "80:80"
  
  ssl:
    image: ivo/portfolio_ssl
    build:
      dockerfile: Dockerfile-ssl
    ports:
      - "443:443"