FROM node:22.17.1-alpine3.22 AS build_step

WORKDIR /home/app/portfolio
COPY ./package-lock.json ./package.json ./angular.json ./tsconfig.app.json ./tsconfig.json ./tsconfig.spec.json ./
COPY ./src ./src

RUN npm install
RUN npm run build

FROM node:22.17.1-alpine3.22 AS delivery_step

RUN adduser -D app
USER app
WORKDIR /home/app/portofolio

COPY --from=build_step /home/app/portfolio/dist ./dist
# Copying built files into /usr/node/dist
COPY --from=build_step /home/app/portfolio/node_modules ./node_modules
COPY ./server.js ./private.key.pem ./public.key.pem ./domain.cert.pem ./

EXPOSE 443
CMD ["node", "server.js", "-ssl"]
# ENTRYPOINT ["node", "server.js", "-ssl"]
